<h3>Hyperplanes and Separators

1.1)<b> General hyperplane, distance to point.</b> <br><br>
Let p be an arbitrary point in R<sup>d</sup>. Give a formula for the signed perpendicular distance from the hyperplane specified by θ,θ<sub>0</sub> to this point p.

<div>
<img src="images/Signed%20Distance.png" width="400"/>
</div>

θ is a column vector with d * 1 dimensions. Ex: For 2D, θ=[θ<sub>1</sub>,θ<sub>2</sub>], and θ<sub>0</sub> is constant<br>
x is a column vector with d * n dimensions. d dimensions and n data points. Ex For 2D, x=[x<sub>1</sub>,x<sub>2</sub>]
<br><br>

<b>Equation of plane :</b><br><br>
<b>Matrix form :</b>
θ<sup>T</sup>x+θ<sub>0</sub>=0 <br> <br>
<b>Dot Product :</b>
θ.x+θ<sub>0</sub>=0

Equation of a plane is given by the dot product of normal vectors and arbitrary points on the plane. θ is the normal vector. x is the point/positional vector on the plane. 


<b>Distance of P from the plane.</b><br><br>
->Normal vector: θ. From Equation of plane.
<br>
->Positional vector: P is a point in the 2D space. Vector from plane to point P is given by P-x. Where x is a arbitrary point on the plane.<br>
Ex: (0,0),(1,2) and (1,-1), (2,1) have same vector (1,2).<br>
->Vector P is perpendicular to the plane. So dot product with Normal vector divided by length of normal vector should give length/distance of P from the plane.<br>
i.e., θ.(P-x)/|θ|=(θ.P-θ.x)/|θ|<br>
θ.x+θ<sub>0</sub> => θ<sub>0</sub>=-θ.x

(θ.P+θ<sub>0</sub>)/|θ| is the distance of P from plane.

<b>Code for signed distance</b>

In [1]:
import numpy as np

data=np.array([[5,2,1,7,1,9,2,3]
             ,[8,3,9,1,0,2,1,8]])
labels=np.array([[1,-1,-1,1,-1,1,-1,1]])
th=np.array([[1],[-1]])
th0=5

In [2]:
def cv(value_list):
    '''Returns column vector'''
    return np.array([value_list]).T

def rv(value_list):
    '''Returns row vector'''
    return np.array([value_list])

def length(col_v):
    return (np.sum((col_v)**2))**(1/2)

def signed_dist(x, th, th0):
    return((np.dot(th.T,x)+th0)/length(th))

signed_dist(data,th,th0)

array([[ 1.41421356,  2.82842712, -2.12132034,  7.77817459,  4.24264069,
         8.48528137,  4.24264069,  0.        ]])

<b>Code for side of hyperplane

Write a Python function that takes as input

->a column vector x<br>
->a column vector th that is of the same dimension as x<br>
->a scalar th0<br><br>
and returns<br><br>
->+1 if x is on the positive side of the hyperplane encoded by (th, th0)<br>
->0 if on the hyperplane<br>
->-1 otherwise.<br>
The answer should be a 2D array (a 1 by 1).

In [3]:
def positive(x, th, th0):
    n = np.sign(signed_dist(x, th, th0))
    return n

positive(data,th,th0)

array([[ 1.,  1., -1.,  1.,  1.,  1.,  1.,  0.]])

<b>Score

Write a procedure that takes as input<br>

<b>data:</b> a d by n array of floats (representing n data points in d dimensions)<br>
<b>labels:</b> a 1 by n array of elements in (+1, -1), representing target labels<br>
<b>th:</b> a d by 1 array of floats that together with<br>
<b>th0:</b> a single scalar or 1 by 1 array, represents a hyperplane<br>
and returns the number of points for which the label is equal to the output of the positive function on the point.

In [4]:
def score(data, labels, th, th0):
    return np.sum(positive(data,th,th0)==labels)

score(data,labels,th,th0)

4

In [5]:
np.array(positive(data,th,th0)==labels)

array([[ True, False,  True,  True, False,  True, False, False]])

<b> Best Separator

Now assume that we have some "candidate" classifiers that we want to pick the best one out of. Assume you have ths, a d by m array of m candidate θ's (each θ has dimension d by 1), and th0s, a 1 by m array of the corresponding m candidate θ<sub>0</sub>'s. Each of the θ, θ<sub>0</sub> pair represents a hyperplane that characterizes a binary classifier.<br>

Write a procedure that takes as input<br>

<b>data:</b> a d by n array of floats (representing n data points in d dimensions)<br>
<b>labels:</b> a 1 by n array of elements in (+1, -1), representing target labels<br>
<b>ths:</b> a d by m array of floats representing m candidate θ's (each θ has dimension d by 1)<br>
<b>th0s:</b> a 1 by m array of the corresponding m candidate θ<sub>0</sub>'s.

and finds the hyperplane with the highest score on the data and labels. In case of a tie, return the first hyperplane with the highest score, in the form of

->a tuple of a d by 1 array and an offset in the form of 1 by 1 array.

In [6]:
def score_all(data, labels, ths, th0s):
   pos =np.sum(positive(data,ths,th0s.T)==labels, axis=1)
   return pos

def best_separator(data, labels, ths, th0s):
    max_index =np.argmax(score_all(data, labels, ths, th0s))
    return cv(ths[:, max_index]),th0s[:, max_index]

ths=np.array([[1,6,2,8],[2,0,-1,11]])
th0s=np.array([[5,-13,9,7]])

score_all(data, labels, ths, th0s), best_separator(data, labels, ths, th0s)

(array([4, 8, 4, 4]),
 (array([[6],
         [0]]), array([-13])))